server:
  port: 9005
spring:
  datasource:
    url: jdbc:mysql://localhost/dr_house_accountancy?useSSL=false
    username: admin
    password: nacs
  jpa:
    hibernate:
      ddl-auto: update
hospital:
  pricelist:
    treatment:
      injection : 10.0
    medicine :
      antibiotic: 11.0
