server:
  port: 9003
spring:
  data:
    mongodb:
      uri: mongodb://localhost/hospital
nurse:
  book:
    asthma: oxigon
    heartattack : emergency
accountancy:
  server:
    url: http://localhost:9005/patients

