server:
  port: 9004
spring:
  data:
    mongodb:
      uri: mongodb://localhost/hospital
apothecary:
  prescription:
    coughing: foster
accountancy:
  server:
    url: http://localhost:9005/patients